name: Android TEST CI

on:
  pull_request:
    branches: [ "develop" ]
    paths:
      - "android/**"

permissions:
  checks: write
  pull-requests: write

jobs:
  android-test:

    runs-on: ubuntu-latest
    env:
      working-directory: ./android

    steps:
      - uses: actions/checkout@v3

      - name: gradle 캐싱
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Java JDK 17 세팅
        if: steps.cache-jdk.outputs.cache-hit != 'true'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
        
      - name: keyStore 세팅
        env:
          KEY_STORE: ${{ secrets.KEY_STORE }}
        run: |
          echo -n "$KEY_STORE" > team201.jks
          base64 -d -i team201.jks
        working-directory: ${{ env.working-directory }}

      - name: keystore properties 생성
        run: touch keystore.properties
        working-directory: ${{ env.working-directory }}
        
      - name: keystore properties 세팅
        env:
          KEY_STORE_PROPERTIES: ${{ secrets.KEY_STORE_PROPERTIES }}
        run:
          echo -e "$KEY_STORE_PROPERTIES" >> keystore.properties
        working-directory: ${{ env.working-directory }}

      - name: local properties 생성
        run: touch local.properties
        working-directory: ${{ env.working-directory }}

      - name: local properties 세팅
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          BASE_TEST_URL: ${{ secrets.BASE_TEST_URL }}
          POLICY: ${{ secrets.POLICY }}
          FIREBASE_APP_VERSION_COLLECTION: ${{ secrets.FIREBASE_APP_VERSION_COLLECTION }}
          GIT_HUB_TEST_URL: ${{ secrets.GIT_HUB_TEST_URL }}
          GIT_HUB_URL: ${{ secrets.GIT_HUB_URL }}
        run:
          echo -e "BASE_URL=\"$BASE_URL\"\n
          BASE_TEST_URL=\"$BASE_TEST_URL\"\n
          POLICY=\"$POLICY\"\n
          FIREBASE_APP_VERSION_COLLECTION=\"$FIREBASE_APP_VERSION_COLLECTION\"\n
          GIT_HUB_TEST_URL=\"$GIT_HUB_TEST_URL\"\n
          GIT_HUB_URL=\"$GIT_HUB_URL\"" >> local.properties
        working-directory: ${{ env.working-directory }}

      - name: google-services json 생성
        run: touch google-services.json
        working-directory: ${{ env.working-directory }}/app

      - name: google-services json 세팅
        env:
          GOOGLE: ${{ secrets.GOOGLE }}
        run: echo "$GOOGLE" >> google-services.json
        working-directory: ${{ env.working-directory }}/app


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ${{ env.working-directory }}

      - name: test 진행
        run: ./gradlew test
        working-directory: ${{ env.working-directory }}

      - name: test 결과
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: |
            ${{ env.working-directory }}/app/build/test-results/*Debug*/*.xml
            ${{ env.working-directory }}/domain/build/test-results/test/*.xml

      - name: 테스트 실패 slack 알림
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: 안드로이드 테스트 실패 알림
          fields: repo, message, commit, author, action, eventName, ref, workflow, job, took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()
