name: 백엔드 배포

on:
  push:
    branches: [BE/chore/docker-test-2]

defaults:
  run:
    working-directory: backend
    
permissions:
  checks: write
  
jobs:
  backend-test:

    runs-on: ubuntu-latest

    steps:
    - name: 체크아웃
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACTION_TOKEN }}
        submodules: recursive
    
    - name: JDK17 설치
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Gradle에 권한부여
      run: chmod +x gradlew

    - name: Test 및 빌드 실행
      run: ./gradlew build

    - name: 도커 메타데이터 설정                  
      id: docker_meta                         
      uses: crazy-max/ghaction-docker-meta@v1 
      with:                                   
        images: yigongil/spring
        tag-semver: |                         
          {{version}}
          {{major}}.{{minor}}
          
    -  name: 도커 허브 로그인
       uses: docker/login-action@v1              
       with:                                          
        username: ${{ secrets.DOCKERHUB_USERNAME }}  
        password: ${{ secrets.DOCKERHUB_TOKEN }} 
        
    -  name: 도커 이미지 빌드 후 허브에 업로드
       uses: docker/build-push-action@v2        
       with: 
          context: .
          file: ./Dockerfile                    
          platforms: linux/amd64                
          push: true                            
          tags: ${{ steps.docker_meta.outputs.tags }}      
          labels: ${{ steps.docker_meta.outputs.labels }}  
        
        
